### ISSUE TITLE
cmgr: Manage log level and missing flags

### ISSUE THREAD

**Issue by royragsdale** [ArmyCyberInstitute/cmgr#7]
Currently the log level is hard coded https://github.com/ArmyCyberInstitute/cmgr/blob/master/cmd/cmgr/main.go#L21. This could be set via an ENV var or CLI flag.

Related to the above, a number of commands are missing the `--verbose` flag that would be useful:
    - `build`
    - `start`
    - `stop`
    - `destroy`
    - `test`

Additionally the `test` command is missing potentially useful testing/debugging options like `--flag-format` and `seed`. An example of where these would be useful is a challenge that has certain constraints on the flag format.

**Comment by jrolli** [comment]
I reduced the verbosity in the main build, but I think I like the idea of controlling it via an ENV variable with "disabled" default for `cmgr` and "warn" default for `cmgrd`.  What would you expect "verbose" to look like for those commands?

**Comment by royragsdale** [comment]
One specific use case I was thinking of is likely covered by controlling logging, e.g. the ability to see which steps are run and how things are detected.

The other was to see more info on intermediate things,such as for a build, to see the metadata, e.g. description/details/artifacts tar location or for an instance to see the port info.

At the moment, as best I can tell, the only way to see these kind of things is via `system-dump`. The motivating scenario was working through why `test` would fail (e.g. early on in a dev cycle) and wanting to walk through each part step by step

**Comment by jrolli** [comment]
Partially addressed the logging level aspect by adding an environment variable (`CMGR_LOGGING`) to adjust the logger level without rebuilding.  Still need to work through the better metadata interface.
